<a href="https://colab.research.google.com/github/mostaf7583/Google-collab/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd;
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv('/data_feature_selection.csv')
df

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x31,x32,x33,x34,x35,x36,x37,x38,x39,y
0,-0.76368,1,65.2,24.8004,2.05,396.90,0.07,403.49,-1.06,0.00632,...,-10.91,-0.19,6.575,2.577405,-6.00,17.11,15.3,0.60,1.93,24.0
1,-2.55269,2,78.9,83.5396,3.26,396.90,8.37,391.81,0.12,0.02731,...,-2.89,5.64,6.421,4.895866,-4.57,-0.91,17.8,0.22,0.33,21.6
2,-0.53271,2,61.1,16.2409,0.51,392.83,6.68,380.05,-0.57,0.02729,...,-0.27,-1.66,7.185,1.942585,-2.66,-0.33,17.8,0.61,0.49,34.7
3,0.98237,3,45.8,8.6436,1.89,394.63,5.46,393.06,0.35,0.03237,...,-0.23,3.48,6.998,1.162967,1.67,0.21,18.7,0.80,0.40,33.4
4,0.39905,3,54.2,28.4089,2.04,396.90,3.61,405.81,0.39,0.06905,...,-7.21,-1.01,7.147,2.800104,6.64,-2.13,18.7,0.42,1.05,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.26263,1,69.1,93.5089,1.73,391.99,7.04,408.06,-1.42,0.06263,...,1.09,2.34,6.593,5.148489,0.50,0.55,21.0,0.36,0.57,22.4
502,0.18527,1,76.7,82.4464,0.78,396.90,11.66,396.48,1.07,0.04527,...,4.30,4.27,6.120,4.866763,-4.24,-0.70,21.0,0.69,1.33,20.6
503,-0.32924,1,91.0,31.8096,0.20,396.90,15.18,407.40,0.15,0.06076,...,-3.01,0.05,6.976,2.992499,-0.18,-0.76,21.0,0.18,1.51,23.9
504,0.29959,1,89.3,41.9904,1.04,393.45,14.15,396.67,-0.30,0.10959,...,9.03,-3.91,6.794,3.492116,-8.27,-1.77,21.0,0.17,1.48,22.0
505,-0.95259,1,80.8,62.0944,3.74,396.90,16.75,403.80,0.97,0.04741,...,2.57,-0.35,6.030,4.261450,-6.02,-0.68,21.0,0.88,0.71,11.9

In [ ]:
x = df.drop('y',axis=1)
y=['y']
y

['y']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)
LR= LinearRegression()
LR.fit(x_train,y_train)

y_prediction =  LR.predict(x_test)
y_prediction

ValueError: ignored